services: 
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    # persist redis data in a named volume
    volumes:
      - redis_data:/data
    restart: unless-stopped
  python-app:
    # build Dockerfile in the current directory
    build: .
    container_name: python
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    # mount the current directory to /app in the container so changes are reflected without rebuilding
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      MSSQL_SA_PASSWORD_FILE: /run/secrets/passwords
      ACCEPT_EULA: "Y"
    secrets:
      - passwords
    ports:
      - "1433:1433"
    restart: unless-stopped
volumes:
  redis_data:

secrets:
  passwords:
    file: ./passwords.txt